from playwright.sync_api import sync_playwright

def wait_for_model(page, accession):
    page.get_by_role("button", name="UniProt", exact=True).click()
    page.locator("input").first.fill(accession)
    page.get_by_role("button", name="Fetch Structure", exact=True).click()
    page.get_by_text(accession, exact=True).last.wait_for(timeout=90000)
    page.wait_for_timeout(5000)

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(viewport={"width": 1440, "height": 900})
    errors = []
    page.on("console", lambda msg: errors.append(f"console:{msg.text}") if msg.type == "error" else None)
    page.on("pageerror", lambda error: errors.append(f"pageerror:{error}"))
    page.goto("http://127.0.0.1:5173/", wait_until="networkidle")
    page.get_by_text("Protein Studio", exact=True).first.click()
    wait_for_model(page, "P0DTC9")
    page.locator("button").filter(has_text="Evidence").last.click(force=True, timeout=60000)
    page.get_by_role("button", name="Compare with AlphaFold", exact=True).first.wait_for(timeout=90000)
    compare_buttons = page.get_by_role("button", name="Compare with AlphaFold", exact=True)
    for _ in range(45):
        if any(compare_buttons.nth(i).is_enabled() for i in range(compare_buttons.count())):
            break
        page.wait_for_timeout(2000)
    compare_button = next(compare_buttons.nth(i) for i in range(compare_buttons.count()) if compare_buttons.nth(i).is_enabled())
    print("P0DTC9 evidence compare enabled", compare_button.is_enabled())
    compare_button.click()
    page.get_by_text("AlphaFold ↔ Experimental Comparison", exact=True).wait_for(timeout=90000)
    page.wait_for_timeout(8000)
    section = page.get_by_text("AlphaFold ↔ Experimental Comparison", exact=True).locator("xpath=ancestor::section[1]")
    initial = section.inner_text()
    print("P0DTC9 initial", {"coverage":"41-174 / 419 aa" in initial, "pairs":"121" in initial, "rmsd":"0.92 Å" in initial, "excluded":"Excluded mapped residues" in initial, "canvas":page.locator("canvas").count()})
    page.screenshot(path="/tmp/protein-studio-p0dtc9-comparison-final.png", full_page=True)
    page.locator("select").last.select_option("B")
    page.get_by_text("126", exact=True).last.wait_for(timeout=30000)
    chain_b = section.inner_text()
    print("chain B", {"pairs":"126" in chain_b, "rmsd":"1.15 Å" in chain_b, "chain_label":"Experimental chain" in chain_b})
    page.evaluate("""() => [...document.querySelectorAll('button')].find((button) => button.textContent.trim() === 'AlphaFold' && button.closest('section'))?.click()""")
    page.evaluate("""() => [...document.querySelectorAll('button')].find((button) => button.textContent.trim() === 'Experimental' && button.closest('section'))?.click()""")
    page.evaluate("""() => [...document.querySelectorAll('button')].find((button) => button.textContent.trim() === 'Matched region only' && button.closest('section'))?.click()""")
    print("toggle controls", {"canvas":page.locator("canvas").count(), "still_summary":"MATCHED Cα PAIRS" in section.inner_text()})
    section.evaluate("section => section.querySelectorAll('button')[section.querySelectorAll('button').length - 1].click()")
    page.get_by_text("Residue Inspector", exact=True).wait_for(timeout=30000)
    inspector_text = page.locator("body").inner_text()
    print("plot selection", {"inspector":"Residue Inspector" in inspector_text, "canonical":"CANONICAL POSITION" in inspector_text})
    page.get_by_role("button", name="Exit Comparison", exact=True).click()
    page.wait_for_timeout(2000)
    print("exit comparison", {"comparison_gone": not page.get_by_text("AlphaFold ↔ Experimental Comparison", exact=True).count(), "structure_tab": page.get_by_role("button", name="Structure", exact=True).count() > 0})
    wait_for_model(page, "P04637")
    page.locator("button").filter(has_text="Evidence").last.click(force=True, timeout=60000)
    page.get_by_text("1TSR", exact=True).first.wait_for(timeout=90000)
    p53_card = page.get_by_text("1TSR", exact=True).first.locator("xpath=ancestor::div[contains(@class, 'rounded-lg')][1]")
    p53_compare = p53_card.get_by_role("button", name="Compare with AlphaFold", exact=True)
    print("P04637 1TSR compare enabled", p53_compare.is_enabled())
    p53_compare.click()
    page.get_by_text("AlphaFold ↔ Experimental Comparison", exact=True).wait_for(timeout=90000)
    p53_text = page.get_by_text("AlphaFold ↔ Experimental Comparison", exact=True).locator("xpath=ancestor::section[1]").inner_text()
    print("P04637 result", {"coverage":"94-312 / 393 aa" in p53_text, "pairs":"196" in p53_text, "rmsd":"1.05 Å" in p53_text, "disclaimer":"does not measure accuracy" in p53_text})
    page.get_by_role("button", name="Exit Comparison", exact=True).click()
    page.locator("button").filter(has_text="Evidence").last.click(force=True, timeout=60000)
    page.route("**/files.rcsb.org/download/**", lambda route: route.abort())
    page.get_by_role("button", name="Compare with AlphaFold", exact=True).first.click()
    page.get_by_text("Comparison unavailable:", exact=False).wait_for(timeout=30000)
    body = page.locator("body").inner_text()
    print("comparison network failure", {"local_error": "Comparison unavailable:" in body, "tabs_present": all(label in body for label in ["Structure", "Biology", "Confidence", "Evidence", "Sequence", "Mutation"])})
    print("console_or_page_errors", errors)
    browser.close()
